### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Marsi591** [xtekky/gpt4free-discord#9]
I get this error at every Model

[2023-06-16 13:41:17] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'create'
Traceback (most recent call last):
  File "C:\Users\Desktop\gpt4free-discord-main\main.py", line 66, in say
    completion = client.send_message(models[model],
KeyError: 'claude'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\Desktop\gpt4free-discord-main\main.py", line 76, in say
    await interaction.response.send_message(f'an error occured: {e}')
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\interactions.py", line 751, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'create' raised an exception: InteractionResponded: This interaction has already been responded to before
ERROR:discord.app_commands.tree:Ignoring exception in command 'create'
Traceback (most recent call last):
  File "C:\Users\Desktop\gpt4free-discord-main\main.py", line 66, in say
    completion = client.send_message(models[model],
KeyError: 'claude'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\Desktop\gpt4free-discord-main\main.py", line 76, in say
    await interaction.response.send_message(f'an error occured: {e}')
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\interactions.py", line 751, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'create' raised an exception: InteractionResponded: This interaction has already been responded to before

**Comment by QuartzWarrior** [comment]
Hey! by chance are you entering "claude" for the model when doing the `/say` command? KeyError means that whatever model was inputted was not found in the models dictionary. If you had entered "claude", well it is obviously not there. try "claude-v1" or "claude-instant" next time.

<details>
<summary>Models Dictionary</summary>

models = {
    'claude-v1': 'a2_2',
    'claude-instant': 'a2',
    'claude-instant-100k': 'a2_100k',
    'sage': 'capybara',
    'gpt-4': 'beaver',
    'gpt-3.5-turbo': 'chinchilla',
}

</details>

**Comment by uk5073970-cyber** [comment]
https://vt.tiktok.com/ZSPYmvUbS/

**Comment by uk5073970-cyber** [comment]
usmanjani28283

**Comment by uk5073970-cyber** [comment]
Please TIKTOK KE I'd ha like me 240k me please https://vt.tiktok.com/ZSPYmvUbS/usmanjani28283

**Comment by uk5073970-cyber** [comment]
@usmanjani28283
